<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<PackageId>XFrame.Kafka</PackageId>
		<Version>10.0.2</Version>
		<Authors>Lwandile Mfundisi</Authors>
		<Description>Kafka integration primitives for .NET applications.</Description>
		<IsPackable>true</IsPackable>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);CopyProjectReferencesToPackage</TargetsForTfmSpecificBuildOutput>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>
	<Target DependsOnTargets="ResolveReferences" Name="CopyProjectReferencesToPackage">
		<ItemGroup>
			<BuildOutputInPackage Include="@(ReferenceCopyLocalPaths-&gt;WithMetadataValue('ReferenceSourceTarget', 'ProjectReference'))" />
		</ItemGroup>
	</Target>
	<ItemGroup>
		<PackageReference Include="Confluent.Kafka" Version="2.6.1" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
		<PackageReference Include="XFrame.Common" Version="9.0.0" />
		<PackageReference Include="XFrame.Ids" Version="9.0.0" />
		<PackageReference Include="XFrame.Resilience" Version="9.0.0" />
		<PackageReference Include="XFrame.ValueObjects" Version="9.0.0" />
	</ItemGroup>
</Project>
